apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: geoai
  labels:
    name: {name}
    app: geoai
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "geoai"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - geoai
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "4504"
          - name: ENVIRONMENT
            value: prod
          - name: LOCAL_URL
            value: http://{name}.gfw.svc.cluster.local:4504
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: EE_PRIVATE_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: EE_PRIVATE_KEY_JSON
        ports:
          - containerPort: 4504
      restartPolicy: Always
