apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geoai
    name: geoai
  name: geoai
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: geoai
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: geoai
    spec:
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "4504"
            - name: ENVIRONMENT
              value: prod
            - name: LOCAL_URL
              value: http://geoai.default.svc.cluster.local:4504
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  key: CT_URL
                  name: mssecrets
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CT_TOKEN
                  name: mssecrets
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  key: CT_REGISTER_MODE
                  name: mssecrets
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  key: API_VERSION
                  name: mssecrets
            - name: EE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: EE_PRIVATE_KEY
                  name: mssecrets
            - name: EE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: EE_ACCOUNT
                  name: mssecrets
          image: skydipper/geoai:master.6
          imagePullPolicy: Always
          name: geoai
          ports:
            - containerPort: 4504
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: type
          operator: Equal
          value: geoai
